### ISSUE TITLE
Crash on launch due to null pointer. Appetite:Frozen_Cod missing.

### ISSUE THREAD

**Issue by JAMalcolmson** [CCr4ft3r/appetite#1]
Caused by: java.lang.NullPointerException: Registry Object not present: appetite:frozen_cod
		at java.util.Objects.requireNonNull(Objects.java:334) ~[?:?] {re:mixin}
		at net.minecraftforge.registries.RegistryObject.get(RegistryObject.java:204) ~[forge-1.19.2-43.2.0-universal.jar%23584!/:?] {re:mixin,re:classloading}
		at ccr4ft3r.appetite.registry.ModRecipes.registerRecipes(ModRecipes.java:23) ~[appetite-1.19.2-1.1.0.jar%23372!/:1.19.2-1.1.0] {re:classloading}
		at ccr4ft3r.appetite.registry.__ModRecipes_registerRecipes_RegisterEvent.invoke(.dynamic) ~[appetite-1.19.2-1.1.0.jar%23372!/:1.19.2-1.1.0] {re:classloading,pl:eventbus:B}
		at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2379!/:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2379!/:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2379!/:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:107) ~[javafmllanguage-1.19.2-43.2.0.jar%23581!/:?] {}
		... 31 more

**Comment by JAMalcolmson** [comment]
On further inspection, this is actually caused by a weird incompatibility with "Better Fences" by winterfoxdev.

**Comment by CCr4ft3r** [comment]
Closed due missing information
